Myproject/Blog/urls.py
from django.urls import path
from . import views
app_name='Blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.details, name='details')
]

Myproject/Myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='HOME'),
    path('blog/', include('Blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Myproject/Blog/models.py
from django.db import models

# Create your models here.
class Blogs(models.Model):
    title=models.CharField(max_length=150)
    date=models.DateField()
    description=models.TextField()

    def __str__(self):
        return self.title

Myproject/portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    discription = models.CharField(max_length=200)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title

Myproject/Blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blogs

# Create your views here.
def all_blogs(request):
    blog=Blogs.objects.order_by('-date')
    return render(request,'blog/blog.html' , {'blogs':blog})

def details(request,blog_id):
    id=get_object_or_404(Blogs,pk=blog_id)
    return render (request,'blog/details.html', {'id':id})

Myproject/portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def Home(request):
    var = Project.objects.all()
    return render(request, 'portfolio/home.html', {'display': var})

Myproject/Blog/templates/blog/blog.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Document</title>
</head>
<body style=" background: rgb(238,174,202);
background: radial-gradient(circle, rgba(238,174,202,1) 0%, rgba(148,184,233,1) 100%);">
<div>

<br><h1 style="text-align: center;
    color:rgb(75, 90, 160);
    width: 30%;
    padding: 10px;
    margin-left: 40%;
    border: 1px solid;
    border-color: transparent transparent;
    box-shadow: 0 10px 10px rgb(148, 148, 148);">URMI's {{ blogs.count }} BLOG{{ blogs.count|pluralize }}</h1><br>


    <br>

    {% for blog in blogs %}
    <div style="display: inline-block; 
        margin: 10px;
        background-color: rgb(185, 143, 185); 
        border: 1px solid gray; 
        box-shadow:0 10px 10px rgb(107, 103, 103); 
        width:405px; 
        padding: 20px;
        text-align: center;
        margin-bottom: 50px;
        margin-left: 13px;">
    <h4 style="color:whitesmoke;"><a href="{% url 'Blog:details' blog.id %}">{{ blog.title }}</a></h4>
    <h5 style="color:rgb(145, 142, 142)">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h5 style="color:whitesmoke">{{ blog.date|date:'M d Y'|upper }}</h5> <br>
    <hr>

</div>
{% endfor %}
</div>
</body>
</html>

Myproject/Blog/templates/blog/details.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Document</title>
</head>
<body style=" background: rgb(238,174,202);
background: radial-gradient(circle, rgba(238,174,202,1) 0%, rgba(148,184,233,1) 100%);">
<div>

<br><h2 style="text-align: center;
    color:rgb(75, 90, 160);
    width: 30%;
    padding: 10px;
    margin-left: 40%;
    border: 1px solid;
    border-color: transparent transparent;
    box-shadow: 0 10px 10px rgb(148, 148, 148);">{{ id.title }}</h2><br>

<br><h5 style="text-align: center;
    color:rgb(216, 216, 216);
    width: 30%;
    padding: 10px;
    margin-left: 40%;
    border: 1px solid;
    border-color: transparent transparent;
    box-shadow: 0 2px 2px rgb(148, 148, 148);">{{ id.date|date:'F jS Y' }}</h5><br>

    <br>
    <h4 style="padding: 5%;">{{ id.description|safe }}</h4>

</div>
</body>
</html>

Myproject/portfolio/templates/portfolio/home.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<div style=" background: rgb(238,174,202);
background: radial-gradient(circle, rgba(238,174,202,1) 0%, rgba(148,184,233,1) 100%);">

<br><h1 style="text-align: center;
    color:rgb(75, 90, 160);
    width: 30%;
    padding: 10px;
    margin-left: 40%;
    border: 1px solid;
    border-color: transparent transparent;
    box-shadow: 0 10px 10px rgb(107, 103, 103);">Urmi's Blog!</h1><br>
{% load static %}
<div style="margin-left:40%;">
    <img src="{% static 'portfolio/Screenshot (399).png' %}" width="50%" style="box-shadow:0 10px 10px rgb(107, 103, 103);"></div><br>

    <h2 class="d-grid gap-2" style="margin:15px;">
        <a href="{% url 'Blog:all_blogs'%}"  class="btn btn-outline-primary btn-lg btn-block">Blog</a></h2>
    <br>

    {% for i in display %}
    <div style="display: inline-block; 
        margin: 10px;
        background-color: rgb(185, 143, 185); 
        border: 1px solid gray; 
        box-shadow:0 10px 10px rgb(107, 103, 103); 
        width:405px; 
        padding: 20px;
        text-align: center;
        margin-bottom: 50px;
        margin-left: 13px;">
    <h4 style="color:whitesmoke;">{{ i.title }}</h4>
    <h5 style="color:whitesmoke">{{ i.discription|truncatechars:50 }}</h5> <br>
    <hr>
    <img src="{{ i.image.url}}" width="250"><br>
    <hr>
    {% if i.url %}
    <a href="{{ i.url }}" style="color: aqua;">{{i.url}}</a>
    {% endif %}
</div>
{% endfor %}
</div>